services:
  auth-service:
    build:
      context: ../docker/php
    container_name: auth_service_php
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}

      APP_SHARE_DIR: ${APP_SHARE_DIR}
      DEFAULT_URI: ${DEFAULT_URI}

      # DB core
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DB_SERVER_VERSION: ${DB_SERVER_VERSION}
      DB_CHARSET: ${DB_CHARSET}

      # service-specific schema
      DB_SCHEMA: ${AUTH_DB_SCHEMA}

      # external services
      REDIS_URL: ${REDIS_URL}

      # API kafka
      KAFKA_GATEWAY_URL: ${KAFKA_GATEWAY_URL}

      # TimeZone
      APP_TIMEZONE: ${TZ}

      APP_NAME: ${AUTH_APP_NAME}
      APP_VERSION: ${AUTH_APP_VERSION}

      AUTH_ACCESS_TOKEN_TTL: ${AUTH_ACCESS_TOKEN_TTL}
      AUTH_REFRESH_TOKEN_TTL: ${AUTH_REFRESH_TOKEN_TTL}

      JWT_PRIVATE_KEY_FILE: ${JWT_CONTAINER_DIR}/private.pem
      JWT_PUBLIC_KEY_FILE: ${JWT_CONTAINER_DIR}/public.pem
      JWT_CONTAINER_DIR: ${JWT_CONTAINER_DIR}
      JWT_AUDIENCE_ACCESS_TOKEN: ${JWT_AUDIENCE_ACCESS_TOKEN}

      DICTIONARY_SERVICE_URL: ${DICTIONARY_SERVICE_URL}

      JWT_CATALOG_ISSUER: ${JWT_CATALOG_ISSUER}

      # unified DSN
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${DB_SERVER_VERSION}&charset=${DB_CHARSET}&options=-csearch_path%3D${AUTH_DB_SCHEMA}"

    volumes:
      - ../../services/auth-service:/var/www/html
      - ${JWT_PRIVATE_KEY_PATH}:${JWT_CONTAINER_DIR}/private.pem:ro
      - ${JWT_PUBLIC_KEY_PATH}:${JWT_CONTAINER_DIR}/public.pem:ro

    working_dir: /var/www/html
    depends_on:
      - postgres
      - redis

    networks:
      - backend
