services:
  dictionaries-service:
    build:
      context: ../docker/php
    container_name: dictionaries_service_php

    environment:
      # =====================
      # APP
      # =====================
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}

      APP_SHARE_DIR: ${APP_SHARE_DIR}
      DEFAULT_URI: ${DEFAULT_URI}

      # =====================
      # POSTGRES
      # =====================
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

      DB_SERVER_VERSION: ${DB_SERVER_VERSION}
      DB_CHARSET: ${DB_CHARSET}

      DB_SCHEMA: ${DICTIONARIES_DB_SCHEMA}

      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${DB_SERVER_VERSION}&charset=${DB_CHARSET}&options=-csearch_path%3D${DICTIONARIES_DB_SCHEMA}"

      # =====================
      # REDIS
      # =====================
      REDIS_URL: ${REDIS_URL}
      DICTIONARY_CACHE_TTL: ${DICTIONARY_CACHE_TTL}
      DICTIONARY_CACHE_VERSION: ${DICTIONARY_CACHE_VERSION}

      KAFKA_GATEWAY_URL: ${KAFKA_GATEWAY_URL}

      APP_TIMEZONE: ${TZ}

      APP_NAME: ${DICTIONARIES_APP_NAME}
      APP_VERSION: ${DICTIONARIES_APP_VERSION}


    volumes:
      - ../../services/dictionaries-service:/var/www/html

    working_dir: /var/www/html

    depends_on:
      - postgres
      - redis

    networks:
      - backend
